//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTestConsole.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHello", ReplyAction="http://tempuri.org/IService1/GetHelloResponse")]
        ServiceTestConsole.ServiceReference1.GetHelloResponse GetHello(ServiceTestConsole.ServiceReference1.GetHelloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHello", ReplyAction="http://tempuri.org/IService1/GetHelloResponse")]
        System.Threading.Tasks.Task<ServiceTestConsole.ServiceReference1.GetHelloResponse> GetHelloAsync(ServiceTestConsole.ServiceReference1.GetHelloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InitUser", ReplyAction="http://tempuri.org/IService1/InitUserResponse")]
        ServiceTestConsole.ServiceReference1.InitUserResponse InitUser(ServiceTestConsole.ServiceReference1.InitUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InitUser", ReplyAction="http://tempuri.org/IService1/InitUserResponse")]
        System.Threading.Tasks.Task<ServiceTestConsole.ServiceReference1.InitUserResponse> InitUserAsync(ServiceTestConsole.ServiceReference1.InitUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHello", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetHelloRequest {
        
        public GetHelloRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHelloResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetHelloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetHelloResult;
        
        public GetHelloResponse() {
        }
        
        public GetHelloResponse(string GetHelloResult) {
            this.GetHelloResult = GetHelloResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InitUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public InitUserRequest() {
        }
        
        public InitUserRequest(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InitUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool InitUserResult;
        
        public InitUserResponse() {
        }
        
        public InitUserResponse(bool InitUserResult) {
            this.InitUserResult = InitUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ServiceTestConsole.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceTestConsole.ServiceReference1.IService1>, ServiceTestConsole.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceTestConsole.ServiceReference1.GetHelloResponse GetHello(ServiceTestConsole.ServiceReference1.GetHelloRequest request) {
            return base.Channel.GetHello(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTestConsole.ServiceReference1.GetHelloResponse> GetHelloAsync(ServiceTestConsole.ServiceReference1.GetHelloRequest request) {
            return base.Channel.GetHelloAsync(request);
        }
        
        public ServiceTestConsole.ServiceReference1.InitUserResponse InitUser(ServiceTestConsole.ServiceReference1.InitUserRequest request) {
            return base.Channel.InitUser(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTestConsole.ServiceReference1.InitUserResponse> InitUserAsync(ServiceTestConsole.ServiceReference1.InitUserRequest request) {
            return base.Channel.InitUserAsync(request);
        }
    }
}
